name: GeoLookup
version: '${project.version}'
main: hoosk.minefurs.Main
api-version: "1.20"
commands:
  geolookup:
    description: Gets player connection information and region
    usage: /geolookup
    aliases: /geo
    permission: geolookup
    permission-message: Sorry, you don't have permission to use this command.
  geolookup-key:
    description: Sets the API key
    usage: /geolookup-key
    permission: op
    permission-message: You must be a server operator to execute this command.