name: GeoLookup
version: '${project.version}'
main: hoosk.minefurs.Main
api-version: "1.18"
commands:
  geolookup:
    description: Gets player connection information and region
    usage: /geolookup
    aliases: /geo
    permission: geolookup
    permission-message: Sorry, you don't have permission to use this command.
